name: Update README with Random Quote

on:
  schedule:
    - cron: '0 0 * * *'   # runs daily at midnight UTC; adjust if you like

jobs:
  update-quote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch a random "humor" quote
        id: fetch_quote
        run: |
          # We do not need an API key—Quotable is free to use.
          RESPONSE=$(curl -s "https://api.quotable.io/random?tags=humor")
          CONTENT=$(echo "$RESPONSE" | jq -r '.content')
          AUTHOR=$(echo "$RESPONSE" | jq -r '.author')
          # Build a Markdown block with an ASCII dash (not a fancy unicode dash):
          FORMATTED="> \"$CONTENT\"  \n> — $AUTHOR"
          echo "::set-output name=quote::$FORMATTED"

      - name: Replace placeholder in README.md
        run: |
          QUOTE="${{ steps.fetch_quote.outputs.quote }}"
          #
          # Use a single-quoted sed script, and escape each literal backslash-newline
          # so that YAML doesn’t interpret it as “another mapping key.”
          #
          sed -i '/<!--QUOTE_START-->/, /<!--QUOTE_END-->/c\
<!--QUOTE_START-->\
'"$QUOTE"'\
<!--QUOTE_END-->' README.md

      - name: Commit & Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git diff --quiet README.md || (
            git add README.md
            git commit -m "chore: update random quote"
            git push
          )
